name: CI Check

on:
  push:
    branches:
      - master
      - apropos
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Afficher un message
        run: echo "GitHub Actions s'est déclenché avec succès !"
